<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Common\**" />
    <Compile Remove="Servicies\**" />
    <EmbeddedResource Remove="Common\**" />
    <EmbeddedResource Remove="Servicies\**" />
    <None Remove="Common\**" />
    <None Remove="Servicies\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="MediatR" Version="12.5.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CMS.Domain\CMS.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\User\Query\" />
  </ItemGroup>

</Project>
