<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>CMS_Clinic_Management_System_</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\css\_Layout.css" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\css\_Layout.css" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CMS.Application\CMS.Application.csproj" />
    <ProjectReference Include="..\CMS.Infrastructure\CMS.Infrastructure.csproj" />
  </ItemGroup>

</Project>
